public enum EBonusEffect
{
	BONUSEFFECT_BOOST,
	BONUSEFFECT_UPSIDE_DOWN,
	BONUSEFFECT_SPIN,
	BONUSEFFECT_SLEPT,
	BONUSEFFECT_ATTRACTED,
	BONUSEFFECT_TELEPORTED,
	BONUSEFFECT_EJECTED,
	BONUSEFFECT_LEVITATE,
	BONUSEFFECT_JUMP,
	BONUSEFFECT_COUNT
}
